apiVersion: v1
kind: Service
metadata:
  name: vulnerable-app
  namespace: lacework
  labels:
    app: vuln-example
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 50000
  selector:
    app: vulnerable-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-app
  namespace: lacework
  labels:
    app: vuln-example
spec:
  selector:
    matchLabels:
      app: vuln-example
  replicas: 1
  template:
    metadata:
      labels:
        app: vuln-example
    spec:
      containers:
      - name: vulnerable-app
        image: ericsixlacework/vulnerable-app:latest
        ports:
        - containerPort: 50000
